import "./App.css";
import errorReader from "error-message-reader";

const App = () => (
  <table>
    <tbody>
      <tr className="title">
        <td>Index</td>
        <td>Raw Log</td>
        <td>Sentence</td>
      </tr>
      {errorMessages.map(
        (msg, index) =>
          errorReader(msg) && (
            <tr key={index} className="data">
              <td>{index + 1}</td>
              <td>{msg}</td>
              <td>{errorReader(msg)}</td>
            </tr>
          )
      )}
    </tbody>
  </table>
);

export default App;

const errorMessages = [
  "out of gas in location: WritePerByte; gasWanted: 100000, gasUsed: 105209: out of gas",
  "out of gas in location: WriteFlat; gasWanted: 120000, gasUsed: 67474: out of gas",
  "out of gas in location: Registering contract to the store; gasWanted: 200000, gasUsed: 53254: out of gas",
  "out of gas in location: ReadPerByte; gasWanted: 1150286, gasUsed: 53304: out of gas",
  "out of gas in location: ReadFlat; gasWanted: 100000, gasUsed: 54974: out of gas",
  "out of gas in location: Loading CosmWasm module: init; gasWanted: 250000, gasUsed: 53274: out of gas",
  "out of gas in location: Loading CosmWasm module: execute; gasWanted: 100000, gasUsed: 59634: out of gas",
  "out of gas in location: Event Cost; gasWanted: 257000, gasUsed: 73363: out of gas",
  "out of gas in location: Delete; gasWanted: 200000, gasUsed: 200121: out of gas",
  "out of gas in location: Contract Execution; gasWanted: 100000, gasUsed: 54904: out of gas",
  "out of gas in location: Compiling WASM Bytes Cost; gasWanted: 1500000, gasUsed: 1762122: out of gas",
  "failed to execute message; message index: 99: Generic error: addr_canonicalize errored: decoding bech32 failed: checksum failed. Expected llclpa, got 6ejs3w.: execute wasm contract failed",
  "failed to execute message; message index: 9: dispatch: Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: unreachable: execute wasm contract failed",
  "failed to execute message; message index: 9: Already claimed: execute wasm contract failed",
  "failed to execute message; message index: 9: 214904994uusd is smaller than 222000000uusd: insufficient funds",
  "failed to execute message; message index: 8: UnavailabledName: execute wasm contract failed",
  "failed to execute message; message index: 5: Max slippage assertion: execute wasm contract failed",
  "failed to execute message; message index: 4: Generic error: addr_canonicalize errored: decoding bech32 failed: invalid character in string: ' ': execute wasm contract failed",
  "failed to execute message; message index: 3: Overflow: Cannot Sub with 2343405 and 2502799: execute wasm contract failed",
  "failed to execute message; message index: 3: no delegation distribution info",
  "failed to execute message; message index: 3: Max spread assertion: execute wasm contract failed",
  "failed to execute message; message index: 3: Max slippage assertion: execute wasm contract failed",
  "failed to execute message; message index: 3: dispatch: Max spread assertion: execute wasm contract failed",
  "failed to execute message; message index: 3: dispatch: dispatch: reply: dispatch: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 29: Generic error: addr_canonicalize errored: decoding bech32 failed: string not all lowercase or all uppercase: execute wasm contract failed",
  "failed to execute message; message index: 23: Generic error: addr_canonicalize errored: decoding bech32 failed: checksum failed. Expected q3lu8p, got q3luxs.: execute wasm contract failed",
  "failed to execute message; message index: 20: Generic error: addr_canonicalize errored: decoding bech32 failed: checksum failed. Expected n6dym9, got ac4d0c.: execute wasm contract failed",
  "failed to execute message; message index: 2: Overflow: Cannot Sub with 103255236 and 103255271: execute wasm contract failed",
  "failed to execute message; message index: 2: Max spread assertion: execute wasm contract failed",
  "failed to execute message; message index: 2: Max slippage assertion: execute wasm contract failed",
  "failed to execute message; message index: 2: Generic error: unauthorized: execute wasm contract failed",
  "failed to execute message; message index: 2: Generic error: addr_canonicalize errored: decoding bech32 failed: checksum failed. Expected qaqg0w, got yekxy0.: execute wasm contract failed",
  "failed to execute message; message index: 2: dispatch: Overflow: Cannot Sub with 943931 and 2000000: execute wasm contract failed",
  "failed to execute message; message index: 2: dispatch: mirror_mint::state::Position not found: execute wasm contract failed",
  "failed to execute message; message index: 2: dispatch: Max spread assertion: execute wasm contract failed",
  "failed to execute message; message index: 2: dispatch: Max slippage assertion: execute wasm contract failed",
  "failed to execute message; message index: 2: dispatch: Generic error: Cannot liquidate more than the position amount: execute wasm contract failed",
  "failed to execute message; message index: 2: dispatch: Generic error: Cannot liquidate a safely collateralized position: execute wasm contract failed",
  "failed to execute message; message index: 2: dispatch: Error parsing into type terraswap::router::Cw20HookMsg: invalid Uint128 '96307863.3' - invalid digit found in string: execute wasm contract failed",
  "failed to execute message; message index: 2: dispatch: Error parsing into type terraswap::pair::Cw20HookMsg: Error parsing decimal '0.0070750000000000006': Generic error: Cannot parse more than 18 fractional digits: execute wasm contract failed",
  "failed to execute message; message index: 2: dispatch: dispatch: Generic error: assertion failed; minimum receive amount: 10013112458, swap amount: 9921403436: execute wasm contract failed",
  "failed to execute message; message index: 2: dispatch: dispatch: dispatch: reply: dispatch: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 2: Asset mismatch: execute wasm contract failed",
  "failed to execute message; message index: 13: 2979298uluna is smaller than 3000000uluna: insufficient funds",
  "failed to execute message; message index: 11: Already claimed: execute wasm contract failed",
  "failed to execute message; message index: 10: no delegation distribution info",
  "failed to execute message; message index: 1: timeout packet verification failed: packet timeout has not been reached for height or timestamp: packet timeout",
  "failed to execute message; message index: 1: receive packet verification failed: block height >= packet timeout height (5-4989639 >= 5-4989634): packet timeout",
  "failed to execute message; message index: 1: Overflow: Cannot Sub with 10051708681 and 10063985461: execute wasm contract failed",
  "failed to execute message; message index: 1: Max spread assertion: execute wasm contract failed",
  "failed to execute message; message index: 1: Max slippage assertion: execute wasm contract failed",
  "failed to execute message; message index: 1: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 1: Generic error: terra1rzr9ahlzamvcgwzpwg6maa7khpu43s8685n6f9 attempting to withdraw 1 of nft",
  "failed to execute message; message index: 1: Generic error: slippage_tolerance cannot bigger than 1: execute wasm contract failed",
  "failed to execute message; message index: 1: Generic error: Price is too old: execute wasm contract failed",
  "failed to execute message; message index: 1: Generic error: order already filled or cancelled: execute wasm contract failed",
  "failed to execute message; message index: 1: Generic error: Native token balance mismatch between the argument and the transferred: execute wasm contract failed",
  "failed to execute message; message index: 1: Generic error: Collateral price is too old: execute wasm contract failed",
  "failed to execute message; message index: 1: Generic error: Cannot withdraw more than you provide: execute wasm contract failed",
  "failed to execute message; message index: 1: Generic error: Cannot withdraw collateral over than minimum collateral ratio: execute wasm contract failed",
  "failed to execute message; message index: 1: Generic error: Cannot mint asset over than min collateral ratio: execute wasm contract failed",
  "failed to execute message; message index: 1: Generic error: addr_canonicalize errored: decoding bech32 failed: checksum failed. Expected qaqg0w, got yekxy0.: execute wasm contract failed",
  "failed to execute message; message index: 1: Generic error: {msg: slippage_tolerance assertion}: execute wasm contract failed",
  "failed to execute message; message index: 1: Error parsing into type terraswap::pair::ExecuteMsg: unknown variant `send`, expected one of `receive`, `provide_liquidity`, `swap`: execute wasm contract failed",
  "failed to execute message; message index: 1: Error parsing into type services::staking::ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 1: Error parsing into type mirror_airdrop::msg::ExecuteMsg: Invalid number.: execute wasm contract failed",
  "failed to execute message; message index: 1: Error parsing into type cw20_legacy::msg::ExecuteMsg: invalid Uint128 '2342.8460400179088' - invalid digit found in string: execute wasm contract failed",
  "failed to execute message; message index: 1: Error parsing into type cw20_legacy::msg::ExecuteMsg: Expected to parse either a `true`, `false`, or a `null`.: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: Overflow: Cannot Sub with 997 and 6069000: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: mirror_mint::state::Position not found: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: Minting cannot exceed the cap: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: Max spread assertion: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: Max slippage assertion: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: Generic error: Cannot liquidate more than the position amount: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: Generic error: Cannot liquidate a safely collateralized position: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: Error parsing into type terraswap::pair::Cw20HookMsg: Error parsing decimal '0.0011013537875704535': Generic error: Cannot parse more than 18 fractional digits: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: dispatch: reply: dispatch: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: dispatch: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: dispatch: Generic error: Gateway/Pool: current blocktime does not satisfies configured deposit time range. origin: (1635339600 ~): execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: dispatch: Gateway/Pool: deposit user cap exceeded. (cap: Uint256(0)): execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: dispatch: dispatch: reply: dispatch: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 1: dispatch: contract terra1nptrquul6qtuj08drysqccnztldvehfud6zec3: not found",
  "failed to execute message; message index: 1: dispatch: Contract exception: execute wasm contract failed",
  "failed to execute message; message index: 1: connection handshake open try failed: connection fields mismatch previous connection fields: invalid connection",
  "failed to execute message; message index: 1: Already claimed: execute wasm contract failed",
  "failed to execute message; message index: 1: 100066919uusd is smaller than 101149000uusd: insufficient funds",
  "failed to execute message; message index: 0: You have to deposit more on prefund contract: execute wasm contract failed",
  "failed to execute message; message index: 0: You have to be kyc verified: execute wasm contract failed",
  "failed to execute message; message index: 0: You have 0 DAO POWER: execute wasm contract failed",
  "failed to execute message; message index: 0: You dont have enough funds: execute wasm contract failed",
  "failed to execute message; message index: 0: You can not have more than `3` pending unbonds: execute wasm contract failed",
  "failed to execute message; message index: 0: You already joined to the IDO: execute wasm contract failed",
  "failed to execute message; message index: 0: You already accepted Terms of Use: execute wasm contract failed",
  "failed to execute message; message index: 0: xyz token supply has been exhausted: execute wasm contract failed",
  "failed to execute message; message index: 0: Verification failed: execute wasm contract failed",
  "failed to execute message; message index: 0: validator not jailed; cannot be unjailed",
  "failed to execute message; message index: 0: uust: no price registered with oracle",
  "failed to execute message; message index: 0: User Not On List: execute wasm contract failed",
  "failed to execute message; message index: 0: User Not Eligible For Active Stage: execute wasm contract failed",
  "failed to execute message; message index: 0: User is trying to withdraw too many tokens: execute wasm contract failed",
  "failed to execute message; message index: 0: User in recruit tier: execute wasm contract failed",
  "failed to execute message; message index: 0: User has already voted: execute wasm contract failed",
  "failed to execute message; message index: 0: User already joined squadron: execute wasm contract failed",
  "failed to execute message; message index: 0: User already has bid for specified collateral: terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp: execute wasm contract failed",
  "failed to execute message; message index: 0: Unlock amount too high; Loan liability becomes greater than borrow limit: 0: execute wasm contract failed",
  "failed to execute message; message index: 0: Unlock amount cannot exceed locked amount: execute wasm contract failed",
  "failed to execute message; message index: 0: UnavailabledName: execute wasm contract failed",
  "failed to execute message; message index: 0: Unauthorized: execute wasm contract failed",
  "failed to execute message; message index: 0: Transfer too big: execute wasm contract failed",
  "failed to execute message; message index: 0: Too much STE to join squadron: execute wasm contract failed",
  "failed to execute message; message index: 0: Toll bridge deadline passed: execute wasm contract failed",
  "failed to execute message; message index: 0: terravaloper108lmrztvc3pc3w774shgvpry4d3lf79k2ummna: no aggregate prevote",
  "failed to execute message; message index: 0: starterra_token::vesting::common::VestingInfo not found: execute wasm contract failed",
  "failed to execute message; message index: 0: Squadron is full: execute wasm contract failed",
  "failed to execute message; message index: 0: spectrum_valkyrie_farm::state::RewardInfo not found: execute wasm contract failed",
  "failed to execute message; message index: 0: spectrum_spec_farm::state::RewardInfo not found: execute wasm contract failed",
  "failed to execute message; message index: 0: spectrum_pylon_farm::state::RewardInfo not found: execute wasm contract failed",
  "failed to execute message; message index: 0: reveal period of submitted vote do not match with registered prevote",
  "failed to execute message; message index: 0: RegistrationDisabled: execute wasm contract failed",
  "failed to execute message; message index: 0: RecommitTooEarly: You can recommit again after 1635850930. Current time is 1635764550.: execute wasm contract failed",
  "failed to execute message; message index: 0: receiving chain block height >= packet timeout height (1-1672678 >= 1-1672623): packet timeout",
  "failed to execute message; message index: 0: Proposal is not open: execute wasm contract failed",
  "failed to execute message; message index: 0: Premium rate cannot exceed the max premium rate: 0.15: execute wasm contract failed",
  "failed to execute message; message index: 0: Poll is not in progress: execute wasm contract failed",
  "failed to execute message; message index: 0: Per-wallet token allotment exceeded: execute wasm contract failed",
  "failed to execute message; message index: 0: Overflow: Cannot Sub with 998539 and 1000000: execute wasm contract failed",
  "failed to execute message; message index: 0: Null/Nil argument: checksum: execute wasm contract failed",
  "failed to execute message; message index: 0: NotOwner: Sender is terra1dfy3rs8h30ul2c4jn45swuqng4f9y3fc77mect, but owner is terra1rmtc8nv3d459ax98va62nf02v63dqd0e566m7t.: execute wasm contract failed",
  "failed to execute message; message index: 0: NotNodeOwner: Sender terra1dfy3rs8h30ul2c4jn45swuqng4f9y3fc77mect is not node owner of [113, 160, 66, 92, 86, 222, 63, 188, 235, 204, 49, 199, 43, 252, 6, 109, 139, 158, 19, 212, 111, 21, 133, 17, 17, 86, 92, 28, 216, 191, 220, 226].: execute wasm contract failed",
  "failed to execute message; message index: 0: Not started: execute wasm contract failed",
  "failed to execute message; message index: 0: Not enough STE to join squadron: execute wasm contract failed",
  "failed to execute message; message index: 0: Not enough STE to join recruit: execute wasm contract failed",
  "failed to execute message; message index: 0: No such option in this poll: execute wasm contract failed",
  "failed to execute message; message index: 0: no delegation for (address, validator) tuple",
  "failed to execute message; message index: 0: no delegation distribution info",
  "failed to execute message; message index: 0: No Active At the moment: execute wasm contract failed",
  "failed to execute message; message index: 0: must be given dc362b8b571141283b7ac445b202db710f21e6b9 not c89862ff70cf3752af07a7f55cc30187f391c802: hash verification failed",
  "failed to execute message; message index: 0: must be given cdaa3113b3ef14ade17d6c1546a3806420c44251 not 7e292ecc6225e88dcca3662e93e0ef98eb4bc52d: hash verification failed",
  "failed to execute message; message index: 0: mNFLX: no price registered with oracle",
  "failed to execute message; message index: 0: mirror_staking::state::RewardInfo not found: execute wasm contract failed",
  "failed to execute message; message index: 0: mirror_limit_order::state::Order not found: execute wasm contract failed",
  "failed to execute message; message index: 0: Minting cannot exceed the cap: execute wasm contract failed",
  "failed to execute message; message index: 0: miaw_lp_staking::state::StakerInfo not found: execute wasm contract failed",
  "failed to execute message; message index: 0: Merkle verification failed: execute wasm contract failed",
  "failed to execute message; message index: 0: Max spread assertion: execute wasm contract failed",
  "failed to execute message; message index: 0: Max slippage assertion: execute wasm contract failed",
  "failed to execute message; message index: 0: InvalidName: execute wasm contract failed",
  "failed to execute message; message index: 0: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 0: InsufficientFund: execute wasm contract failed",
  "failed to execute message; message index: 0: Index Fund has expired: execute wasm contract failed",
  "failed to execute message; message index: 0: IDO is closed: execute wasm contract failed",
  "failed to execute message; message index: 0: ibc/0471F1C4E7AFD3F07702BEF6DC365268D64570F7C1FDC98EA6098DD6DE59817B: no price registered with oracle",
  "failed to execute message; message index: 0: Generic error: you already outbid: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Wallet does not own NFT: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Wait for the unbonding period: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Verification is failed: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: VaaAlreadyExecuted: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: User is trying to withdraw too many tokens.: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: User has already voted.: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: unauthorized: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Unauthorized: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Ticker symbol is not in expected format [a-zA-Z-]{3,12}: instantiate wasm contract failed",
  "failed to execute message; message index: 0: Generic error: There are no unlockable funds for the provided positions: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: terra1x9dd8dhcj6t5tvmvmzahudqup638dh48jpfmk3 attempting to withdraw 1500000 of native",
  "failed to execute message; message index: 0: Generic error: terra1dkaqje55sw5rq8npdxdf7p9zkhjr307ckk9d28 attempting to withdraw 1 of nft",
  "failed to execute message; message index: 0: Generic error: Task is still in progress: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Sold out: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Requested amount is bigger than claim amount: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: request submitted too late: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Querier contract error: Generic error: Price is too old: contract query failed: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Price is too old: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Poll is not in progress: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Poll is not in passed status: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: order already filled or cancelled: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: order already expired: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Only whitelisted wallets can call: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Nothing to withdraw: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Not exist referral reward: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Not exist participation reward: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Not enough balance: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: No withdrawable uluna assets are available yet: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: No task in progress.: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: No rewards have accrued yet: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: No bids with the specified information exist: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Native token balance mismatch between the argument and the transferred: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Max allowed number of planets discovered!: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: invalid maker: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Existing discover is still in progress: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Exceeded per address reservation limit: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Decrease amount cannot exceed user balance: 999715: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: claiming too often: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Cannot withdraw collateral over than minimum collateral ratio: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Cannot unbond more than bond amount: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Cannot mint asset over than min collateral ratio: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Cannot complete a task for moving nft.: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: cannot adjust premium before premium_min_update_interval passed: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Candy Machine is Soldout: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Candy Machine is not yet open: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: Can not open a position with low collateral ratio than minimum: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: bid amount too low: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: auth failed: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: auction is over: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: auction is not end: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: auction is already started: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: already settled: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: already claimed: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: all NFTs sold out!: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: addr_validate errored: decoding bech32 failed: string not all lowercase or all uppercase: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: addr_validate errored: decoding bech32 failed: invalid index of 1: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: addr_validate errored: decoding bech32 failed: invalid bech32 string length 2: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: addr_validate errored: decoding bech32 failed: checksum failed. Expected 4x5m36, got ewrsdf.: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: addr_canonicalize errored: decoding bech32 failed: checksum failed. Expected llclpa, got 6ejs3w.: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: {msg: slippage_tolerance assertion}: execute wasm contract failed",
  "failed to execute message; message index: 0: Generic error: {msg: negative total output (1000000 -> 991186) (l:8814)}: execute wasm contract failed",
  "failed to execute message; message index: 0: Gateway/Swap: refund not allowed after token release: execute wasm contract failed",
  "failed to execute message; message index: 0: Gateway/Swap: earn not allowed before lock period: execute wasm contract failed",
  "failed to execute message; message index: 0: failed to delegate; 976657uluna is smaller than 976659uluna: insufficient funds",
  "failed to execute message; message index: 0: execute msg size is too huge: exceeds max contract msg size limit",
  "failed to execute message; message index: 0: Error parsing into type valkyrie::campaign::execute_msgs::ExecuteMsg: invalid Uint128 '-3105' - invalid digit found in string: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::router::ExecuteMsg: unknown variant `send`, expected one of `receive`, `execute_swap_operations`, `execute_swap_operation`, `assert_minimum_receive`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::router::ExecuteMsg: unknown variant `eyJleGVjdXRlX3N3YXBfb3BlcmF0aW9ucyI6IHsib3BlcmF0aW9ucyI6IFt7InRlcnJhX3N3YXAiOiB7ImFza19hc3NldF9pbmZvIjogeyJ0b2tlbiI6IHsiY29udHJhY3RfYWRkciI6ICJ0ZXJyYTFkazNnNTNqczMwMzR4NHY1YzN2YXZoajI3Mzh1bmU4ODB5dTZreCJ9fSwgIm9mZmVyX2Fzc2V0X2luZm8iOiB7Im5hdGl2ZV90b2tlbiI6IHsiZGVub20iOiAidXVzZCJ9fX19LCB7InRlcnJhX3N3YXAiOiB7ImFza19hc3NldF9pbmZvIjogeyJ0b2tlbiI6IHsiY29udHJhY3RfYWRkciI6ICJ0ZXJyYTFkemh6dWt5ZXp2MGV0ejIydWQ5NDB6N2FkeXY3eGdjamthaHV1biJ9fSwgIm9mZmVyX2Fzc2V0X2luZm8iOiB7InRva2VuIjogeyJjb250cmFjdF9hZGRyIjogInRlcnJhMWRrM2c1M2pzMzAzNHg0djVjM3ZhdmhqMjczOHVuZTg4MHl1Nmt4In19fX0sIHsidGVycmFfc3dhcCI6IHsiYXNrX2Fzc2V0X2luZm8iOiB7Im5hdGl2ZV90b2tlbiI6IHsiZGVub20iOiAidXVzZCJ9fSwgIm9mZmVyX2Fzc2V0X2luZm8iOiB7InRva2VuIjogeyJjb250cmFjdF9hZGRyIjogInRlcnJhMWR6aHp1a3llenYwZXR6MjJ1ZDk0MHo3YWR5djd4Z2Nqa2FodXVuIn19fX1dLCAib2ZmZXJfYW1vdW50IjogMTAwMDAwMCwgIm1pbmltdW1fcmVjZWl2ZSI6IDEwMTAwMDAuMH19`, expected one of `receive`, `execute_swap_operations`, `execute_swap_operation`, `assert_minimum_receive`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::router::ExecuteMsg: invalid Uint128 '213810.3' - invalid digit found in string: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::router::ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::pair::ExecuteMsg: unknown variant `send`, expected one of `receive`, `provide_liquidity`, `swap`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::pair::ExecuteMsg: unknown variant `eyJzd2FwIjogeyJiZWxpZWZfcHJpY2UiOiAiMzAwMCIsICJtYXhfc3ByZWFkIjogIjAuMDAxIiwgIm9mZmVyX2Fzc2V0IjogeyJhbW91bnQiOiAiNTAwMDAwMDAwMCIsICJpbmZvIjogeyJuYXRpdmVfdG9rZW4iOiB7ImRlbm9tIjogInV1c2QifX19fX0=`, expected one of `receive`, `provide_liquidity`, `swap`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::pair::ExecuteMsg: unknown variant `coins`, expected one of `receive`, `provide_liquidity`, `swap`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::pair::ExecuteMsg: unknown variant `auto_stake`, expected one of `receive`, `provide_liquidity`, `swap`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::pair::ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::pair::ExecuteMsg: Expected to parse either a `true`, `false`, or a `null`.: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::pair::ExecuteMsg: Expected this character to start a JSON value.: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::pair::ExecuteMsg: Error parsing decimal '1.00300902708e-7': Generic error: Error parsing fractional: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type terraswap::pair::ExecuteMsg: Error parsing decimal '': Generic error: Error parsing whole: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type starterra_token::vesting::regular::ExecuteMsg: unknown variant `eyJjbGFpbSI6eyJhbW91bnQiOiIxMzY0NzgyNTc3In19`, expected one of `update_config`, `register_vesting_accounts`, `submit_to_claim`, `claim`, `emergency_withdraw`, `withdraw_to_burning`, `accept_ownership`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type starterra_token::vesting::regular::ExecuteMsg: unknown variant `eyJjbGFpbSI6eyJhbW91bnQiOiIxMzY0MDAwMDAwIn19`, expected one of `update_config`, `register_vesting_accounts`, `submit_to_claim`, `claim`, `emergency_withdraw`, `withdraw_to_burning`, `accept_ownership`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type starterra_token::staking::ExecuteMsg: unknown variant `eyJzdWJtaXRfdG9fdW5ib25kIjp7ImFtb3VudCI6IjUwMDAwMDAwIn19`, expected one of `receive`, `submit_to_unbond`, `unbond`, `move_bond`, `withdraw`, `burning_withdraw`, `update_config`, `emergency_withdraw`, `accept_ownership`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type starterra_token::squadron_users::ExecuteMsg: missing field `id`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type pylon_token::gov::ExecuteMsg: unknown variant `eyJ3aXRoZHJhd192b3RpbmdfdG9rZW5zIjp7ImFtb3VudCI6IjUwMjU2NjU0MCJ9fQ==`, expected one of `receive`, `execute_poll_msgs`, `register_contracts`, `update_config`, `cast_vote`, `withdraw_voting_tokens`, `end_poll`, `execute_poll`, `snapshot_poll`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type pylon_token::airdrop::ExecuteMsg: unknown variant `eyJjbGFpbSI6eyJhbW91bnQiOiIxMjM3ODQwNyIsInByb29mIjpbImU4OTY5NTQwMTQ5M2Y3ZWQ4YjI2YzA5Mzg0NjlkMzBlNWY4YjJjMWMxMDZkODNkZjljMDRjNDgxMzA3YmQyMDUiLCJmOTFiMDUwMTdhYzVlMjk4MTAwNmVhOTk1MmRmYjQzZDIxZTk3NmU5NDk2YjhhOTY1MGY4NzAwZDFmNjJjNDQ3IiwiNDJkMmZjNWEwZGIyOTlmMjMwOTc3ZGY3NmU5N2ZkZGM2YTYwN2RlNmIxMGI1MzczODRkZmI0MGQyMzYwNTVkNSIsImJkNmNmN2NhN2ViZWU1OTk5ZTQ2ZjY5YzU0Mzc3MmYzN2ViZGZmMTM4YWQzOGExNWRlMWU4NmZhOWIzOGM2NTEiLCJjZWE0YzkzZmQ0MmRkNGI0N2YyY2NjMDIzMWI5NzczOGM4NDI4NGRkMjQzMWJkOTI3MzBjYmM1NzIyYTljMGJmIiwiM2QwYTc4OTgwNmJlMDRiZjQ5ZDE5ZDQxOTlmOGI4ODA2ZjhlNDlhYjJiMDU0MDdjMWQxYWI4OGY4ODdlNGZlNSIsIjQ2MTk0ODg4M2EyMGIxZGUyNjQ0YzgyYTc2Yjg3MThjZDAwZWQ2NjFmMWFiYjYxNjlmYThjNmVlYzAyMTZkMTMiLCI5Mjc2Y2M2YjAwYzk2YmUwZTMwMWZiYTU5MGVhZjExYTYyMjUxNTNhYTAyNDVjMzkwYzc3NTViNWY0OWViOTRlIiwiOWNhMTdlMjQ2ZDMzNzM3ZjkxYjIxNTM4ZGVjODY1NDU2NjBkOTNmODgwNTBjYzY4YzI3NjUxMzQ1ODcyYmQwMCIsImM1ZmEzNmJiYmY5OGZkNjAzZWNiNzY3NzdmNjBiNWVlZDQ2MDY5MTgyZWU4MGM2Yzc4ZWFiZjgzMDQ5OTdkMWYiLCJlNzEyM2QwZWM2YTcxZTdkMjgwMDE0ZTQyOGM4MGYyOTM0MTg3M2E4NjYxOGQ1NWIyZTQ1NTRjNmNmYTUxMDI4IiwiNWUwN2YwZTBmNjBlMGMxMTAwMzM4ZTNlZDIzYjk1OTYxNzMzY2NiM2RjMDc4NjY5YTdhYjg4NzFmOGU0ZGQxMiIsImQ4NTk0OTY0NmY3NDEzZWZmNjI0ZjQzOTE2NTliN2UzM2I2NDNhZjEzM2FlNDY0OWI1OTY3MDJhZWVjZWYyMGEiLCI1NTIwZTZiZjc5MDlkNDI2NmU5MmU1MzVmYzczNTJjY2Q2YzZkZGUwZmYwZDI1NzRiNTliMjQ1N2Y0NWZjMmEyIl0sInN0YWdlIjoxNX19`, expected one of `update_config`, `register_merkle_root`, `claim`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type pylon_gateway::swap_msg::ExecuteMsg: unknown variant `anyone`, expected one of `configure`, `deposit`, `withdraw`, `claim`, `earn`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type pylon_gateway::pool_msg::ExecuteMsg: unknown variant `eyJ3aXRoZHJhdyI6eyJhbW91bnQiOiI0OTg3MTQ3NzUyIn19`, expected one of `receive`, `update`, `withdraw`, `claim`, `deposit_internal`, `withdraw_internal`, `claim_internal`, `configure`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type my_first_contract::msg::InstantiateMsg: u128 is not supported: instantiate wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type my_first_contract::msg::ExecuteMsg: unknown variant `try_reset`, expected `increment` or `reset`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type my_first_contract::msg::ExecuteMsg: unknown variant `try_increment`, expected `increment` or `reset`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type my_first_contract::msg::ExecuteMsg: unknown variant `Increment`, expected `increment` or `reset`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type my_first_contract::msg::ExecuteMsg: missing field `monday`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type my_first_contract::msg::ExecuteMsg: missing field `counter`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type my_first_contract::msg::ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type moneymarket::oracle::ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type moneymarket::market::ExecuteMsg: unknown variant `eyJkZXBvc2l0X3N0YWJsZSI6e319`, expected one of `receive`, `register_contracts`, `update_config`, `repay_stable_from_liquidation`, `execute_epoch_operations`, `deposit_stable`, `borrow_stable`, `repay_stable`, `claim_rewards`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type moneymarket::market::ExecuteMsg: invalid Uint256 '2987076.7': execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type moneymarket::liquidation::ExecuteMsg: unknown variant `eyJzdWJtaXRfYmlkIjp7ImNvbGxhdGVyYWxfdG9rZW4iOiJ0ZXJyYTFrYzg3bXU0NjBmd2txdGUyOXJxdWg0aGMyMG01NGZ4d3RzeDdncCIsInByZW1pdW1fcmF0ZSI6IjAuMDEifX0=`, expected one of `receive`, `update_config`, `submit_bid`, `retract_bid`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type moneymarket::liquidation::ExecuteMsg: unknown variant `eyJyZXRyYWN0X2JpZCI6eyJjb2xsYXRlcmFsX3Rva2VuIjoidGVycmExa2M4N211NDYwZndrcXRlMjlycXVoNGhjMjBtNTRmeHd0c3g3Z3AifX0=`, expected one of `receive`, `update_config`, `submit_bid`, `retract_bid`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type moneymarket::liquidation_queue::ExecuteMsg: missing field `premium_slot`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type moneymarket::liquidation_queue::ExecuteMsg: missing field `bid_idx`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type moneymarket::liquidation_queue::ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type moneymarket::liquidation_queue::ExecuteMsg: Expected this character to be either a `','` or a `'}'`.: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type mirror_protocol::staking::ExecuteMsg: unknown variant `eyJ3aXRoZHJhdyI6e319`, expected one of `receive`, `update_config`, `register_asset`, `unbond`, `withdraw`, `auto_stake`, `auto_stake_hook`, `adjust_premium`, `increase_short_token`, `decrease_short_token`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type mirror_protocol::lock::ExecuteMsg: unknown variant `eyJ1bmxvY2tfcG9zaXRpb25fZnVuZHMiOnsicG9zaXRpb25zX2lkeCI6WyIyODg4NSJdfX0=`, expected one of `update_config`, `lock_position_funds_hook`, `unlock_position_funds`, `release_position_funds`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type mirror_airdrop::msg::ExecuteMsg: unknown variant `eyJjbGFpbSI6eyJhbW91bnQiOiI1MDM3MDUiLCJzdGFnZSI6MjAsInByb29mIjpbImYyYTM1MjAyZThlOTI3N2ZiZDY1ZGI2NWJjYjE0NzE2MGI0MjFlMTc3YmM3ZmE0NzM5ZmFjYWM3NGM5YTIxMDkiLCJlMTZkNTk0MDhiYTkwMzRlNWU2NTRiZGY0MmYyZGI4MzEyMWJiOGZmOWU3M2ExZjA4ZWY0ZTJkM2ExYTc3YWEzIiwiMzMzYzIwZjk1NjgwYTFmNmE0NDliNmEyNTEzNThiMThiYTFmNDJlZDU3MDZjZGNjOWQ0M2NhOThmMGUxZmM3MSIsImUxYTY0MDg2MDEwODUyYzc0MjI2ZTMyNGFiZTI2NjBjZTVmMTc0OGVmYmFjY2QzZGRhNWM4YjI4MGM4NmY2MDAiLCI4NjI4YTM3Y2VhZTFhMjlhOWE0NjgzNTMwNmExYWVkNDEwOTJkNTBkM2Q0ODdlODI2MjQxNmRiMzJiMWI0YTY4IiwiMjZiMzdhYzRkYWI0ODc3OTVjN2UzYWVhZjI5MTY5YWM5NDUyNmU5ZDViODNlNzYwYTk5NTE4OGFkNzg2NmVjOSIsIjhiMTM4MDdlMjA1ODI1NTI1YjJmYmM1NmFiNDQzMzAwMzM0MDgyNWNlMDExNmE5Y2FjMWZmZTdlZTYxZGMyNjMiLCJiZWI3ZjFiNWYxNDc0NmUwYjVkYjZmOTY5NGYzN2Y2NTE5ZTgzYmEwNzllMmZmMzdhMDYxZTBiN2EwMDBiZTBmIiwiNWI4ZDEzOGNhNzQxMzBjYTAzZTExNTdiNTUyMWMyZDRlOGQ1NTg5OWU3ZjVjNGQwMWZhOTYyMjI4YTNiODU3OSIsIjUyNjNiNzI4MmI4ZjY4MDE4MDQ5MTNlNDc3MjBlMDU2ODkwY2I2ZDFmOWQ0OTEwMmY3OTZiMmVkZTkxN2IzMWIiLCJlNTIzMWU4ZDFjYzJkN2QxMzE4MTI5NjUzYjM4YmNmMjdjMzNmNzhhMzliNDgyMGI1NjE0ZmJhMmVhYzI0MmNjIiwiOGNmODEyNmRlMGI4M2NmYWM3NTMwNDNkZjNiNzExNWZiMDdmNmMwMjg5MTIxYjA3NzM3ODQ3NDNhNjkzYTkxZSJdfX0=`, expected one of `update_config`, `update_merkle_root`, `register_merkle_root`, `claim`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type mirror_airdrop::msg::ExecuteMsg: Invalid number.: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type loterra::msg::ExecuteMsg: unknown variant `get_ticket`, expected one of `register`, `play`, `claim`, `collect`, `poll`, `vote`, `present_poll`, `reject_poll`, `safe_lock`, `renounce`, `receive`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type loot::token::ExecuteMsg: missing field `token_id`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type loopswap::pair::ExecuteMsg: unknown variant `send`, expected one of `receive`, `provide_liquidity`, `swap`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type loopswap::pair::ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20::msg::Cw20ExecuteMsg: unknown variant `swap`, expected one of `transfer`, `burn`, `send`, `increase_allowance`, `decrease_allowance`, `transfer_from`, `send_from`, `burn_from`, `mint`, `update_marketing`, `upload_logo`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20::msg::Cw20ExecuteMsg: missing field `recipient`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20::msg::Cw20ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20_merkle_airdrop::msg::ExecuteMsg: unknown variant `eyJjbGFpbSI6eyJhbW91bnQiOiI1OTkxNjI1MCIsInByb29mIjpbIjRlOWFmMTRkMmE1ZWJiYjk4YTVhMDlmYTIwZWYzMDZlYjE0MzdjMmM4ZWNkODc3OTBiMjBkODZhN2FlN2QzNGQiLCIzN2RjNGQxYTEyOGU2YTA0NGRkYjdmMzEwNmE1ODAzZWUwN2M4NDRmYWJkOGM0MmViODRlMjUwMmM4OWI2MjA1IiwiNzAwOWVjYmI2MjY1OTI4ZmU2ZThiNDljZDhjMDczMTBiOGY5MDE3ZDRlOWUwMmFkZjBhYmYxNzdiY2QxZDI1NCIsImI2MWJlNDYwODMxODdjZjljYjkxNDVjZGY3ZmVmYmJlZTAzNGRmZGMyZDM5ZWI4ZTM0MWRmYzQyOTllNzBmY2EiLCIwZjdjNzI2M2YxYmQxZmMyODZjYTAxNjlhNjNmYjllZjg5OWNmNzBlODExYzQzY2U0ZGI1NjFkOTE5ZTNmNTk0IiwiZTAyOWE4Yzk1ZDBkODhjYzA0Y2IyZjFlYmVhNDhlNDNiMTU5MmExNmVmNmU5ODU4MDJjOWI5ZjhkZDE2ZWQwMSIsIjdhYzg2OWEzYTNkNWY1YWZlZjcyMzMwNmQwYjVlM2RiOGViNDNmNTkwNjg1ZjQ0N2FkZmU1N2UxYTE4YmM4N2YiLCIzMzY3MDhlNTUzYTE5NzBmMzNlNDY4NjJkNmRmY2FkNjc4NzlmNDBjOTc2MzBiNDU5NzRhMTFkNDgzMTkwZGEzIiwiNWY4NDZhYmI1YTkwMDFhN2Q1OTU2ZjIxNDU1NGRmNDA3NmYzZDE2OTAyYWEyNzRmMmIwMGQ1NGIxOTVmNTNmMSIsIjQzNjgyMDY5ZGJhNDIwNjVjMDJjY2M4YzVlOWM5MWQwZWRlMDE0MzlmMTViYTVkNWY0NDk4YzNiOTU1NzliYTIiLCI4NDgxN2UxYzc2MjliNWQ4MDMwNjNlOGM1OTVmYTY2ZGI3YjAxNzE4YTE0NmE4MWQ2YWM5NGFmMTFlN2E0YmY3IiwiMjAxYTZmMGVjZGNjNTM2M2UwOGFkNmU5NTIxNmY2NTViMTU5NDU3NmJjOTVhZTEyYTdkMTgxNTlhNjJhMDdhOCIsImUwNWEzMWQ2MWE2YjdiNjcyMGFkMTk5NjkzMjA3MDM1NzBhZjVjMWI5ZThhZDk2NGFlY2I0MTRjZDk0NGQzNTgiLCI5M2VhNDE3ZTQxMGQxOWE2MDY4ZTQxOGExNTM2ZWJmOWZlMDJjNjhlZjkwNjQyYmRhYWU2M2MxNTRjNWYzNmE4IiwiZGI1ZTMxZTVhNTg3ZTNlNzBiZmJmMDA3N2E3NzJkZTI2MGFiZWIyZDk3ODJiNzE3MzEyMTJlMTNkOWEyNGFjMyIsIjMyZjlmMDU0ODJiOTlmZmYxOGQyZDJlZDgwZDQxODI5OGY1ZDk5NGJkZmZmNGE4ZWJmMGFmZGZlNTIyYTBmMGMiXSwic3RhZ2UiOjN9fQ==`, expected one of `update_config`, `register_merkle_root`, `claim`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20_legacy::msg::ExecuteMsg: unknown variant `eyJzd2FwIjp7Im1heF9zcHJlYWQiOiIwLjAwNSIsImJlbGllZl9wcmljZSI6Ijc5MC45NzcyODU2NjQ1MDkxNzc3MTMifX0`, expected one of `transfer`, `burn`, `send`, `mint`, `increase_allowance`, `decrease_allowance`, `transfer_from`, `send_from`, `burn_from`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20_legacy::msg::ExecuteMsg: unknown variant `{'send': {'amount': '20000000', 'contract': 'terra178jydtjvj4gw8earkgnqc80c3hrmqj4kw2welz', 'msg': 'eyJzd2FwIjp7Im1heF9zcHJlYWQiOiIwLjE1MCIsImJlbGllZl9wcmljZSI6IjEyMDAwMC4wIn19'}}`, expected one of `transfer`, `burn`, `send`, `mint`, `increase_allowance`, `decrease_allowance`, `transfer_from`, `send_from`, `burn_from`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20_legacy::msg::ExecuteMsg: missing field `msg`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20_legacy::msg::ExecuteMsg: invalid Uint128 '32272.000000000004' - invalid digit found in string: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20_legacy::msg::ExecuteMsg: invalid Uint128 '' - cannot parse integer from empty string: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20_legacy::msg::ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20_legacy::msg::ExecuteMsg: invalid base64: {'swap': {'max_spread': '0.150', 'belief_price': '1099.8162357084686'}}: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20_legacy::msg::ExecuteMsg: Expected to parse either a `true`, `false`, or a `null`.: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20_elastic::msg::ExecuteMsg: invalid Uint128 '7580196.3' - invalid digit found in string: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type cw20_elastic::msg::ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type candy_machine_minter::msg::InstantiateMsg: Invalid type: instantiate wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type base::msg::InstantiateMsg: missing field `count`: instantiate wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type base::msg::ExecuteMsg: unknown variant `Reset`, expected `increment` or `resetmonday`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type base::msg::ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type aperture_amadeus::msg::ExecuteMsg: unknown variant `claim_tokens_from_wormhole_and_delta_neutral_invest`, expected one of `claim_short_sale_proceeds_and_stake`, `close_short_position`, `delta_neutral_invest`, `do`, `reinvest`, `set_controller`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type angel_core::messages::index_fund::ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type anchor_token::airdrop::ExecuteMsg: unknown variant `eyJjbGFpbSI6eyJzdGFnZSI6MjUsImFtb3VudCI6IjcxNjAiLCJwcm9vZiI6WyJlOGZkOWI3M2QxZjYyNzQwNjk1NzFjM2EwYjIwMGRhMjgwZjczMDI1YWNmOTk0ZmFjMjZkZWZiMzlmYWZlNzRkIiwiMDE0MWIwN2QyNzVmYzM2MjRlZGZlZjcxY2QwM2RkMzU3ZDAwYzcxNGNkODBmMDJjMmMzM2JjYzMwYjczNTliMiIsIjgzNmRmMTg3YTVlOTQwOTBiOWFkMmY4YjQ0ZGI5MzRiODI2Y2M5YWQ1ZTRhNDZhZTY1Yzk3ZmQ3NzVlMTBmMzUiLCI4Nzg2MTEyYzhlZDNjMTQyYTMwMzYwZjdkMDVhOWFmZTRkYTVjYzllZDAxMzNmNjBjYWU3MWFmMGUxMjZhOGU0IiwiZTg3YmQ3N2QyY2UzNjg0MjQ4ZmYxMGVkZWMwZDEwODliNDhkODUzY2I5ZDMzN2NjMDIzYjc0ZTEzZmRkZTM3NiIsIjk1MDJkN2U2ZmRkZjk5YjNhNjZiYzkzNmU0YWYzNjkyZGEyM2QyZGM2MjBhNTlkYjFkNGZkODc1MTZiMDZiZjEiLCJhZGQwMmVkM2YyOGVhYjhhYzhiMTY3YTc3NjlmOWZmNjY4NDg2NzFmMmIzMzA2NzIxMmVlZmE1ZGI0NGJmNWVlIiwiZGNiYzVlMzIxOTlhMGQ1NTVhNjYyMDUxMDIxN2VjNzNkYzc1MmMzYzUzZTk3MDU4MDIzNTc3OTY1MmEyMDBjOSIsIjI3NDJkN2RjYWY3MzIyNDVmNjc4NWNiYTUwZjJlZjgwZjlhMTk2YzAwOTUyNDBkY2FjNTc3ZDE4ZjBkNzU0MDEiLCI3YjhmYzM1MmJlODA4MmZhMzlhZTgwYmNkNWVjMWRkNzAzZTY1MzNmNWVjZTVmYTAyYzljMzc3MzM2NmY3MjkxIiwiMTg4OGE3OWU5MjM0MGZmYTI0OGRmZTY3YmQzZDhjYTVhNjE3NGZiN2ZiM2U5YjgwNmYyNzFhYTU3NGJiODMzNyIsImVmZGJhY2Y3MTJhZTRjOTA5OTc2MWVlYjEyMzQ4OTBjODVmZDc2ZDM3MGM5ZGM5N2EzNWExM2MyNmY5N2JkNjciLCI5NWViMThiMjNlMWU4YzhjYWNmOWI3MjQ0ZTNiYjgxZWJmMGQyNDUzNDc3MzMwNThkMDA4MzU2OTcwMTY5YjlmIiwiYmI1MGNjN2FjODg4MzAyZmFkNjc0Y2JiZmE3MzU3YzY3MDA2OGIxZjY3YzAyYmFlMzRiYTEyMWYxZmY4MTViNSIsIjg5MjUyNGQ1ZGZiMGY5NTI0MGNjNjEwYTM2NmMwNTA3ZTkxNDQ1MmJjNTBmY2NhYzQ3NGVjMjFhY2IzMGE4NDkiXX19`, expected one of `update_config`, `register_merkle_root`, `claim`: execute wasm contract failed",
  "failed to execute message; message index: 0: Error parsing into type anchor_token::airdrop::ExecuteMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: unreachable: instantiate wasm contract failed",
  "failed to execute message; message index: 0: Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: unreachable: execute wasm contract failed",
  "failed to execute message; message index: 0: Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: unreachable",
  "failed to execute message; message index: 0: Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: Error calling into the VM's backend: Panic in FFI call: execute wasm contract failed",
  "failed to execute message; message index: 0: Do tasks to claim more: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: User already staking in other contract: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Unauthorized: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: u64 not found: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Transfer too big: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: TotalMintLimit: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: reply: Swap failed: reply wasm contract failed",
  "failed to execute message; message index: 0: dispatch: reply: Drand round already added 1344143: reply wasm contract failed",
  "failed to execute message; message index: 0: dispatch: reply: dispatch: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: reply: dispatch: dispatch: dispatch: 0uusd: invalid coins",
  "failed to execute message; message index: 0: dispatch: Overflow: Cannot Sub with 803878 and 1620000: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: No allowance for this account: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: mirror_mint::state::Position not found: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Minting cannot exceed the cap: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: MaxQtyMinted: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Max spread assertion: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: User is trying to unstake too many tokens.: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: User balance is zero: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: unauthorized: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: swap output doesn't met the expected_out 10118750, got 10088151: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: Strategy deposits paused: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: reserve price too low: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: Querier contract error: terraswap::asset::PairInfoRaw not found: contract query failed: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: Querier contract error: Generic error: addr_canonicalize errored: Input is empty: contract query failed: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: Price is too old: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: invalid cw20 hook message: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: Error parsing into type loot::auction::Cw721HookMsg: invalid Uint128 '-11000000' - invalid digit found in string: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: Description too long: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: Collateral price is too old: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: Cannot withdraw more than user balance: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: Cannot liquidate more than the position amount: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Generic error: assertion failed; minimum receive amount: 1000000, swap amount: 22899: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Gateway/Pool: withdraw amount exceeds balance. (balance: Uint256(21999859)): execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Error parsing into type terraswap::router::Cw20HookMsg: invalid Uint128 '-102495485440' - invalid digit found in string: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Error parsing into type terraswap::pair::Cw20HookMsg: unknown variant `redeem_stable`, expected `swap` or `withdraw_liquidity`: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Error parsing into type terraswap::pair::Cw20HookMsg: Invalid type: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Error parsing into type terraswap::pair::Cw20HookMsg: Error parsing decimal '1.85626391617e-7': Generic error: Error parsing fractional: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Error parsing into type terraswap::pair::Cw20HookMsg: Error parsing decimal '0.00023353057852619564': Generic error: Cannot parse more than 18 fractional digits: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Error parsing into type terraswap::pair::Cw20HookMsg: Error parsing decimal '-0.0030853049': Generic error: Error parsing whole: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Error parsing into type terraswap::pair::Cw20HookMsg: EOF while parsing a JSON value.: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Error parsing into type cw20_legacy::msg::ExecuteMsg: unknown variant `receive`, expected one of `transfer`, `burn`, `send`, `mint`, `increase_allowance`, `decrease_allowance`, `transfer_from`, `send_from`, `burn_from`: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: unreachable: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: unreachable",
  "failed to execute message; message index: 0: dispatch: dispatch: Unauthorized: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: Transfer too big: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: reply: dispatch: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: reply: dispatch: dispatch: dispatch: 0uusd: invalid coins",
  "failed to execute message; message index: 0: dispatch: dispatch: Max spread assertion: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: Generic error: UST balance post arbitrage = 19967283397 is less than initial UST balance = 19986968637: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: Generic error: assertion failed; minimum receive amount: 1011748225, swap amount: 1005981270: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: unreachable: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: dispatch: reply: dispatch: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: dispatch: reply: dispatch: dispatch: Generic error: collateral is too small: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: dispatch: Max spread assertion: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: dispatch: Invalid zero amount: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: dispatch: Generic error: No bids with the specified information exist: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: dispatch: dispatch: Max spread assertion: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: dispatch: dispatch: Generic error: swap output 1008098249 is lower than initial uusd 1016943947: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: dispatch: dispatch: dispatch: dispatch: Generic error: swap output 1003884889 is lower than initial uusd 1016943947: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: dispatch: 0uusd: invalid coins",
  "failed to execute message; message index: 0: dispatch: dispatch: 0uluna: invalid coins",
  "failed to execute message; message index: 0: dispatch: Cannot Sub with 11265104215 and 12516638845: execute wasm contract failed",
  "failed to execute message; message index: 0: dispatch: 9861uusd is smaller than 10023uusd: insufficient funds",
  "failed to execute message; message index: 0: dispatch: 0uusd: invalid coins",
  "failed to execute message; message index: 0: dispatch: 0uusd is smaller than 1uusd: insufficient funds",
  "failed to execute message; message index: 0: Different fraction: execute wasm contract failed",
  "failed to execute message; message index: 0: Coordinates already claimed: execute wasm contract failed",
  "failed to execute message; message index: 0: contract terra12r9gsugqja2d6arumlfuca9xj8ygp3du38kcnu: not found",
  "failed to execute message; message index: 0: Contract exception: execute wasm contract failed",
  "failed to execute message; message index: 0: ConsumeNonexistCommitment: The commitment 09b68fffe7d5bd3a3cd32d719921fe344ddc15b186b90ad59fdc5491a3bde5cf does not exist.: execute wasm contract failed",
  "failed to execute message; message index: 0: constractInfo terra1y8q286sj3w3vrpd6m0q0l0haswql83qxxx6yst: not found",
  "failed to execute message; message index: 0: connection handshake open init failed: 07-tendermint-1544: light client not found",
  "failed to execute message; message index: 0: CommitmentIsTooEarlyOrExpired: The commitment matures at 1635859379 and expires at 1635945759. Current time is 1635859378.: execute wasm contract failed",
  "failed to execute message; message index: 0: commission cannot be changed more than once in 24h",
  "failed to execute message; message index: 0: commission cannot be changed more than max change rate",
  "failed to execute message; message index: 0: Cannot unbond more than pending unbond amount: execute wasm contract failed",
  "failed to execute message; message index: 0: Cannot submit to unbond more than bond amount: execute wasm contract failed",
  "failed to execute message; message index: 0: Cannot set to own account: execute wasm contract failed",
  "failed to execute message; message index: 0: Cannot liquidate safely collateralized loan: execute wasm contract failed",
  "failed to execute message; message index: 0: Cannot Exceed the Reservation Limit: execute wasm contract failed",
  "failed to execute message; message index: 0: Cancelled Due To Slippage: execute wasm contract failed",
  "failed to execute message; message index: 0: Borrow amount too high; Loan liability becomes greater than borrow limit: 150951523286: execute wasm contract failed",
  "failed to execute message; message index: 0: Bonus Already Claimed: execute wasm contract failed",
  "failed to execute message; message index: 0: auction::state::Auction not found: execute wasm contract failed",
  "failed to execute message; message index: 0: AlreadySolved: execute wasm contract failed",
  "failed to execute message; message index: 0: Already voted on this proposal: execute wasm contract failed",
  "failed to execute message; message index: 0: Already claimed: execute wasm contract failed",
  "failed to execute message; message index: 0: alloc::vec::Vec<alloc::string::String> not found: execute wasm contract failed",
  "failed to execute message; message index: 0: alloc::string::String not found: execute wasm contract failed",
  "failed to execute message; message index: 0: 999999uluna is smaller than 1000000uluna: insufficient funds",
  "failed to execute message; message index: 0: 0samoleans is smaller than 999samoleans: insufficient funds",
  "failed to execute message; message index: 0: 0ibc/9117A26BA81E29FA4F78F57DC2BD90CD3D26848101BA880445F119B22A1E254E is smaller than 200000ibc/9117A26BA81E29FA4F78F57DC2BD90CD3D26848101BA880445F119B22A1E254E: insufficient funds",
  "block height: 4961550, timeout height: 4961549: tx timeout height",
  "account sequence mismatch, expected 1000517, got 1000497: incorrect account sequence",
];
